
<script>
  var streamWindow = null;
  var mmWindow = null;
  function openStreamWindow() {
    streamWindow = window.open("https://swib22-stream.collocall.de", "SWIB22 Livestream", "top=0,left=0,width=800,height=600,status=no,toolbar=no,location=no,menubar=no,titlebar=no");
  }
  function openMMWindow() {
    mmWindow = window.open("https://swib22.collochat.de/swib/channels/town-square", "SWIB22 Mattermost", "top=40,left=40,width=400,height=600,status=no,toolbar=no,location=no,menubar=no,titlebar=no");
  }
</script>

## SWIB22 – 14th Semantic Web in Libraries Conference - Now!

**Starting every day at 14:00 h UTC**

<table width="100%">
<tr><td width="50%">
<button onclick="openStreamWindow()" title="Opens window with Livestream" style="width:100%; height:10em; background-color:#056098; color:#ffffff; font-size:1.5em"><strong>&blacktriangleright; Follow the livestream</strong></button>
</td>
<td width="50%">
<button onclick="openMMWindow()" title="Opens window with Mattermost Conference Chat" style="width:100%; height:7em; background-color:#056098; color:#ffffff; font-size:1.5em"><strong>Participate in the discussions</strong>
<span style="font-size:0.7em"><br />*Please register beforehand, and receive&#160;account details</span> </button>
<form action="https://www.conftool.org/swib22/register.php"title="To Conftool registration page"  target="_blank"><button style="width:100%; height:3em; background-color:#056098; color:#ffffff; font-size:1.5em"><strong>Register now</strong></button></form>
</td></tr>
</table>

We plan to upload recordings of the SWIB22 conference sessions.


## About the SWIB conference


