### 15th SWIB

**Save the date**\
SWIB23: 11.-13.9.2023 in Berlin (Germany)\
2.12.2022

### 14th SWIB

**SWIB22 finished**\
900 registrations from 58 countries\
[Slides and videos are online](../swib22/programme.html)\
2.12.2022

**300 registrations from 35 countries within 24 hours**\
The first workshops are fully booked already.\
19.10.2022

**Registration opened**\
18.10.2022

**CfP published**\
09.05.2022

### 13th SWIB

**[SWIB21 slides and videos are now online](../swib21/programme.html)**\
08.12.2021

