**Livestream from SWIB will not be available this year**\
We will try to provide recordings afterwards.\
10.08.2023

**SWIB23 programme published & registration opened**\
13.07.2023

**CfP published**\
27.02.2023

**SWIB23 – Save the date**\
11.–13. September 2023 in Berlin (Germany)\
02.12.2022

### 14th SWIB

**SWIB22 finished**\
900 registrations from 58 countries\
[Slides and videos are online](../swib22/programme.html) ([Youtube playlist](https://www.youtube.com/playlist?list=PL7fMsenbLiQ2xcclhSnk1nv752E4N_Nqx))\
2.12.2022
