### 14th SWIB

**More than 750 registrations from over 50 countries**\
[Registration is still open](https://swib.org/swib22/registration.html).\
25.11.2022

**300 registrations from 35 countries within 24 hours**\
The first workshops are fully booked already.\
19.10.2022

**Registration opened**\
18.10.2022

**CfP published**\
09.05.2022

### 13th SWIB

**[SWIB21 slides and videos are now online](../swib21/programme.html)**\
08.12.2021

